name: Build and Test on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
    
permissions:
  contents: read
  packages: read

jobs:
  build:

    runs-on: windows-latest
    steps:
    - name: Checkout code including submodules
      uses: actions/checkout@v2
      with:
        token: '${{ secrets.ACCESS_TOKEN }}'
        submodules: 'true'
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish --configuration Release -o build
    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: roddbwpf
        path: build/